apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- pipelinerun.yaml
secretGenerator:
- name: aws
  files:
  - credentials=awsCredentials.txt
  - config=awsConfig.txt
configurations:
- kustomizeconfig.yaml
